GET http://localhost:3000/tasks/

###
GET http://127.0.0.1:3000/tasks/status/Pendiente


###

GET http://localhost:3000/tasks/65122064666491b2da4bf618

###

POST http://localhost:3000/tasks/
Content-Type: application/json

{
    "name": "Tarea",
    "description": "Realizar la siguiente tarea",
    "status": "Pendiente"
    
}

###

DELETE http://127.0.0.1:3000/tasks/651220fbe74433685d38bd51

###

PATCH http://localhost:3000/tasks/65122064666491b2da4bf618
Content-Type: application/json

{
    "name": "Nueva tarea",
    "discription": "Tarea actualizada",
    "status": "Realizada"
}


